modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Weever1337/GravityProject/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = 'https://boosty.to/weever
    authors = "${mod_authors}"
    logoFile = "logo.png"
    credits = ""
    description = 'This mod adds Gravity library to Minecraft 1.16.5 with Forge.'

[[dependencies.${ mod_id }]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${ mod_id }]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"